// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBplEotbyUCro_lzTWR3PYJt15cF4U_Y',
    appId: '1:688494126520:web:a475410f690796aff5db4d',
    messagingSenderId: '688494126520',
    projectId: 'findsonaweb',
    authDomain: 'findsonaweb.firebaseapp.com',
    storageBucket: 'findsonaweb.appspot.com',
    measurementId: 'G-59S4PD1Q78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRM0ZqkcCj-uQqVnSd3Udn5U693AT67lg',
    appId: '1:688494126520:android:a186ff7eb71bab70f5db4d',
    messagingSenderId: '688494126520',
    projectId: 'findsonaweb',
    storageBucket: 'findsonaweb.appspot.com',
  );
}
